### PR TITLE
fix: local vs deployed inbox indicator icon | 48

### LINKED ISSUE #48: Update inbox list to indicate whether or not a graph is local or deployed
I'm thinking a small blue circle (tooltip saying local) next to the inbox name for inboxes which are local (deployment url starts with http instead of https), but open to ideas. In the end there should be a very clear way to indicate an inbox points to a local graph vs a deployed graph.

### PR DESCRIPTION
**Pull request by starmorph**
Add Icon next to Inbox to indicate whether it is a local or cloud deployment.

fixes #48

Screenshot 2025-04-15 at 2 08 51 PM

### CODE REVIEW

File: src/components/app-sidebar/index.tsx [hunk 1]
```diff
@@ -65,6 +65,13 @@ function hashString(str: string): number {
   return Math.abs(hash);
 }
 
+/**
+ * Determines if a URL is a local development URL.
+ */
+function isLocalUrl(url: string): boolean {
+  return url.startsWith("http://") || url.includes("localhost");
+}
```
Comment (bracesproul) [inline src/components/app-sidebar/index.tsx:73]: left a similar comment in another PR, but this should be moved to a shared util file, and only check if it has `https`, since some local URLs dont necessarily contain http:// or localhost, but all prod urls will have https

**Review by bracesproul — CHANGES_REQUESTED** [review]
see feedback in slack dms

**Comment by starmorph** [comment]
Screenshot 2025-04-15 at 3 29 48 PM

next version
moved util func to shared utils file

File: src/components/app-sidebar/index.tsx [hunk 2]
```diff
@@ -144,9 +106,12 @@ export function AppSidebar() {
                               </span>
                             </SidebarMenuButton>
                           </TooltipTrigger>
-                          <TooltipContent>{label}</TooltipContent>
+                          <TooltipContent>
+                            {label} - {isDeployed ? "Deployed" : "Local"}
```
Comment (bracesproul) [inline src/components/app-sidebar/index.tsx:110]: nice touch

**Review by bracesproul — APPROVED** [review]
lgtm, thank you!
