### PR TITLE
Dylan/fix studio urls fixes 51

### LINKED ISSUE #51: Fix opening in studio for deployed URLs

### PR DESCRIPTION
**Pull request by starmorph**
fixes #51 

**Refactor: Update LangSmith Studio URL Construction for Deployed Graphs**

This PR updates how "Open in Studio" URLs are generated for deployed LangGraph instances to align with the new format required by LangSmith Studio (`/studio/thread?organizationId=...&hostProjectId=...&threadId=...`).

**Changes:**

*   Added `tenantId` to the `AgentInbox` type (`src/components/agent-inbox/types.ts`).
*   Updated the "Add Inbox" dialog (`src/components/agent-inbox/components/add-agent-inbox-dialog.tsx`) to fetch and store the `tenantId` from the deployment's `/info` endpoint.
*   Added a utility (`extractProjectId`) to parse the project ID from the `AgentInbox.id` for deployed graphs (`src/components/agent-inbox/utils.ts`).
*   Modified `constructOpenInStudioURL` (`src/components/agent-inbox/utils.ts`) to use `tenantId` and `projectId` for deployed graph URLs and accept the full `AgentInbox` object.
*   Updated `GenericInboxItem` (`src/components/agent-inbox/components/generic-inbox-item.tsx`) and `ThreadActionsView` (`src/components/agent-inbox/components/thread-actions-view.tsx`) to pass the `AgentInbox` object to the utility.
*   Fixed a bug in `GenericInboxItem` where a `NextLink` wrapper caused double navigation attempts for the Studio button.

**Result:**

Users can now correctly open threads associated with deployed LangGraph instances directly in LangSmith Studio using the "Studio" button within the Agent Inbox component. Error handling is included for cases where necessary data (`tenantId`, `projectId`) might be missing.

### CODE REVIEW

File: src/components/agent-inbox/utils.ts [hunk 1]
```diff
@@ -95,20 +104,56 @@ export function unknownToPrettyDate(input: unknown): string | undefined {
...
+    // This might be incorrect if the intention is different for local.
+    const smithStudioURL = new URL(smithStudioBaseUrl);
+    // trim the trailing slash from deploymentUrl
+    const trimmedDeploymentUrl = inbox.deploymentUrl.replace(/\/$/, "");
+
+    if (threadId) {
+      // The original logic appended threadId to the path, which might be wrong.
+      // Let's try adding it as a query param for now, similar to deployed.
+      // Revisit if local URLs need a different structure.
+      // smithStudioURL.pathname += `/${threadId}`; // Original way
```
Comment (bracesproul) [inline src/components/agent-inbox/utils.ts:148]: tested locally, what you're doing works so im going to drop these comments
```suggestion
    // --- Logic for local/non-deployed URLs ---
    const smithStudioURL = new URL(smithStudioBaseUrl);
    const trimmedDeploymentUrl = inbox.deploymentUrl.replace(/\/$/, "");

    if (threadId) {
```

File: src/components/agent-inbox/utils.ts [hunk 2]
```diff
@@ -285,3 +330,19 @@ export async function fetchDeploymentInfo(
...
+    return null;
+  }
+  const parts = inboxId.split(":");
+  if (parts.length === 2) {
+    // Basic check if the first part looks like a UUID v4
+    const uuidV4Regex =
+      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
+    if (uuidV4Regex.test(parts[0])) {
+      return parts[0];
+    }
```
Comment (bracesproul) [inline src/components/agent-inbox/utils.ts:345]: uuid exports a `validate` func, we should use that

**Review by bracesproul — APPROVED** [review]
lgtm, going to make one push to docs & update the code, then I'll merge. thank you!!
