### PR TITLE
fix: popover staying open: replace popover with dropdown

### LINKED ISSUE #62: Inbox popover doesn't close when I close the edit inbox dialog
https://www.loom.com/share/65e20ad7abe1450d91baa8273b3884ec

Need to add a callback which sets the popover `open` state to `false` when the dialog `open` state changes to `false`

### PR DESCRIPTION
**Pull request by starmorph**
fixes #62 

Replaced popover component with dropdown component as popover's and dialogs seem to both be forms of modals that conflict with each other / dropdown menu works for this purpose

### CODE REVIEW

File: src/components/app-sidebar/index.tsx [hunk 1]
```diff
@@ -119,36 +125,42 @@ export function AppSidebar() {
...
+                        <DropdownMenuContent align="end" className="w-40">
+                          <DropdownMenuItem
+                            className="cursor-pointer flex items-center gap-2"
                             onClick={(e) => {
                               e.stopPropagation();
+                              // Find the Edit button in the EditAgentInboxDialog and click it
+                              const editButton = document.querySelector(
+                                `[data-agent-inbox-id="${item.id}"]`
+                              ) as HTMLButtonElement;
+                              editButton?.click();
```
Comment (bracesproul) [inline src/components/app-sidebar/index.tsx:143]: is this to close it?

Comment (bracesproul) [reply src/components/app-sidebar/index.tsx:143]: if thats the case, i would update the comment to make it clear, and add a comment in the `edit-agent-inbox-dialog.tsx` file where it's defined to make sure no one deletes/changes on accident

**Review by bracesproul — APPROVED** [review]
lgtm, with one nit

**Comment by starmorph** [comment]
This is a good implementation example of a dropdown that opens a dialog in Radix UI (particularly number 2) 

https://codesandbox.io/p/sandbox/dropdownmenu-dialog-items-r9sq1q?file=%2Fsrc%2FApp.js

File: src/components/agent-inbox/components/dropdown-and-dialog.tsx [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+}) {
+  const [dropdownOpen, setDropdownOpen] = React.useState(false);
+  const [dialogOpen, setDialogOpen] = React.useState(false);
+
+  // When dialog opens, close dropdown
+  React.useEffect(() => {
+    if (dialogOpen) {
+      setDropdownOpen(false);
+    }
+  }, [dialogOpen]);
```
Comment (bracesproul) [inline src/components/agent-inbox/components/dropdown-and-dialog.tsx:31]: instead of using a `useEffect`, can we just tap into the `onOpenChange` prop on `Dialog`, or would that not work?

Comment (bracesproul) [reply src/components/agent-inbox/components/dropdown-and-dialog.tsx:31]: or the onClick handlers in the buttons? If neither of these work, then `useEffect` can do

**Review by bracesproul — APPROVED** [review]
