### PR TITLE
fix: change view scroll 53 v2

### LINKED ISSUE #53: Fix scroll position when returning to inbox view from thread view
When you enter an interrupted thread view, scroll, then return (back arrow button in the UI), your view is scrolled to the same position as in the thread view. This should ideally be the same scroll position you were in when you clicked on the thread

### PR DESCRIPTION
**Pull request by starmorph**
<div>
    <a href="https://www.loom.com/share/263e21a64b414ae88b3575bafff3d307">
      <p>Scroll Functionality Loom - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/263e21a64b414ae88b3575bafff3d307">
      
    </a>
  </div>

fixes #53 
fixes #56 

# PR: Scroll Position Persistence Between Views

## Problem Solved
This PR fixes scroll position behavior when navigating through the application:
- List view preserves scroll position when returning from thread views
- Thread detail views always start at the top
- Works across multiple navigation sequences (list → thread → back to list → another thread → back to list)

## Implementation
Created a custom scroll position management system using:
- A `useScrollPosition` hook to save/restore scroll positions
- Intelligent detection of scrollable elements
- Multiple restoration attempts to ensure reliable positioning

## Key Technical Features
1. Ref-based position tracking that persists across navigation
2. Smart detection of which element is actually scrolling
3. Multiple restoration attempts with delayed timing
4. Event throttling for performance optimization

## Benefits
- Better UX: Users don't lose their place when navigating back
- Consistent behavior: Thread views start at top, list views maintain position
- Resilient implementation: Works across different navigation paths

The implementation is lightweight, isolated, and significantly improves navigation fluidity in the application.

### CODE REVIEW

File: src/components/agent-inbox/inbox-view.tsx [hunk 1]
```diff
@@ -49,18 +102,59 @@ export function AgentInboxView<
...
+          return;
+        }
+      });
+    }
+  };
+
+  // And remove the Container ref set console log
+  React.useEffect(() => {
+    // Just track ref setup without logging
+  }, [containerRef.current]);
```
Comment (bracesproul) [inline src/components/agent-inbox/inbox-view.tsx:140]: whats this?

File: src/components/agent-inbox/index.tsx [hunk 2]
```diff
@@ -4,16 +4,82 @@ import { INBOX_PARAM, VIEW_STATE_THREAD_QUERY_PARAM } from "./constants";
...
 >() {
   const { searchParams, updateQueryParams, getSearchParam } = useQueryParams();
   const [selectedInbox, setSelectedInbox] =
     React.useState<ThreadStatusWithAll>("interrupted");
+  const { saveScrollPosition, restoreScrollPosition } = useScrollPosition();
+  const containerRef = React.useRef<HTMLDivElement>(null);
 
   const selectedThreadIdParam = searchParams.get(VIEW_STATE_THREAD_QUERY_PARAM);
   const isStateViewOpen = !!selectedThreadIdParam;
+  const prevIsStateViewOpen = React.useRef<boolean>(false);
```
Comment (bracesproul) [inline src/components/agent-inbox/index.tsx:20]: nit, it can infer from the default value
```suggestion
  const prevIsStateViewOpen = React.useRef(false);
```

File: src/components/agent-inbox/index.tsx [hunk 3]
```diff
@@ -4,16 +4,82 @@ import { INBOX_PARAM, VIEW_STATE_THREAD_QUERY_PARAM } from "./constants";
...
+      for (let i = 0; i < maxAttempts; i++) {
+        setTimeout(
+          () => {
+            if (containerRef.current) {
+              restoreScrollPosition(containerRef.current);
+            }
+          },
+          50 * (i + 1)
+        );
+      }
```
Comment (bracesproul) [inline src/components/agent-inbox/index.tsx:63]: is whats causing the slight flicker i see in the loom when you go back & it resets the scroll position? I guess I'm not entirely clear on why we need delays?

File: src/components/agent-inbox/index.tsx [hunk 4]
```diff
@@ -4,16 +4,82 @@ import { INBOX_PARAM, VIEW_STATE_THREAD_QUERY_PARAM } from "./constants";
...
+    }
+    // Case 3: Switching between different thread views
+    else if (
+      prevIsStateViewOpen.current &&
+      isStateViewOpen &&
+      lastThreadId.current !== selectedThreadIdParam
+    ) {
+      // No action needed when switching between thread views
+    }
```
Comment (bracesproul) [inline src/components/agent-inbox/index.tsx:72]: if we're not taking any action we can drop this?
```suggestion
```

File: src/components/agent-inbox/hooks/use-scroll-position.tsx [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+      }
+
+      // Use requestAnimationFrame to ensure DOM updates have completed
+      window.requestAnimationFrame(() => {
+        // Try the provided element first
+        if (element && elementType === "element") {
+          element.scrollTop = position;
+        } else {
+          // Fall back to window scroll
+          window.scrollTo(0, position);
```
Comment (bracesproul) [inline src/components/agent-inbox/hooks/use-scroll-position.tsx:50]: small nit, but i think there's an arg we can pass to this which makes the scroll "smooth"

smoothScroll or something? If I'm hallucinating this, ignore.

File: src/components/agent-inbox/components/interrupted-inbox-item.tsx [hunk 6]
```diff
@@ -34,14 +35,26 @@ export function InterruptedInboxItem<
...
+      onThreadClick();
+    }
+
+    // Small delay to ensure scroll position is captured before navigation
+    setTimeout(() => {
+      updateQueryParams(
+        VIEW_STATE_THREAD_QUERY_PARAM,
+        threadData.thread.thread_id
+      );
+    }, 50);
```
Comment (bracesproul) [inline src/components/agent-inbox/components/interrupted-inbox-item.tsx:52]: Same as below, but why the delay?

**Review by bracesproul — APPROVED** [review]
couple questions/nits, but lgtm overall.

Plz resolve the comments, then you can merge on your own. ty!
