### PR TITLE
fix: add edit inboxes #47

### LINKED ISSUE #47: Allow for editing inboxes
We should replace the delete button with an ellipses, which opens a popover that can either delete, or click an edit button which should open a dialog for editing all of the fields set when creating it

### PR DESCRIPTION
**Pull request by starmorph**
Fixes #47

### Preview
Screenshot 2025-04-15 at 10 44 30 AM

### changes 
- delete inbox icon  --> Elipses menu popover to edit or delete
 - create  new component `src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx`

### CODE REVIEW

File: src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx [hunk 1]
```diff
@@ -0,0 +1,223 @@
...
+  );
+  const [name, setName] = React.useState(agentInbox.name || "");
+
+  React.useEffect(() => {
+    if (open) {
+      setGraphId(agentInbox.graphId);
+      setDeploymentUrl(agentInbox.deploymentUrl);
+      setName(agentInbox.name || "");
+    }
+  }, [open, agentInbox]);
```
Comment (bracesproul) [inline src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx:48]: Do we need this if we're assigning these state vars these fields by default from the props?

File: src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx [hunk 2]
```diff
@@ -0,0 +1,223 @@
...
+
+  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
```
Comment (bracesproul) [inline src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx:50]: This would be a larger change, but I created a new issue [here](https://github.com/langchain-ai/agent-inbox/issues/58) for adding a hook to manage inboxes. Lets implement that first, then use the `editInboxes` method in this handler instead of one-off logic here

File: src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx [hunk 3]
```diff
@@ -0,0 +1,223 @@
...
+      toast({
+        title: "Error",
+        description: "Failed to update agent inbox",
+        variant: "destructive",
+        duration: 3000,
+      });
+    }
+  };
+
+  const isDeployedGraph = deploymentUrl.includes("default.us.langgraph.app");
```
Comment (bracesproul) [inline src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx:106]: I know I've done this in other places in the repo, but we should change it to:
1. be a shared util `isDeployedGraph`
2. update the logic to instead check if the url starts with `https` as I believe self hosted LGP graphs wont necessarily have the `langgraph.app` domain

File: src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx [hunk 4]
```diff
@@ -0,0 +1,223 @@
...
+  const showLangChainApiKeyField =
+    langchainApiKey !== undefined &&
+    handleChangeLangChainApiKey &&
+    isDeployedGraph;
```
Comment (bracesproul) [inline src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx:110]: We shouldn't allow for setting/updating API key in this dialog, the Settings popover handles that

**Review by bracesproul — DISMISSED** [review]

File: src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx (hunk 2 above)
Comment (bracesproul) [reply src/components/agent-inbox/components/edit-agent-inbox-dialog.tsx:43]: doesnt look like you're using/added a method on the `useInboxes` hook for editing an inbox?

**Review by bracesproul — APPROVED** [review]
